name: Laravel
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Copy env files
        run: |
          cp .env.example .env
          cp .env.laradock laradock/.env

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: docker-${{ github.sha }}

      - name: Start Docker containers
        run: docker compose -f laradock/docker-compose.yml up -d mysql

      - name: Wait for MySQL
        run: |
          sleep 15
          docker compose -f laradock/docker-compose.yml exec -T mysql mysqladmin ping -h localhost -uroot -p123123

      - name: Install composer dependencies
        run: docker compose -f laradock/docker-compose.yml exec -T workspace composer install --no-interaction --prefer-dist

      - name: Generate Laravel APP_KEY
        run: docker compose -f laradock/docker-compose.yml exec -T workspace php artisan key:generate --force

      - name: Install npm dependencies
        run: docker compose -f laradock/docker-compose.yml exec -T workspace npm install

      - name: Run build script (npn run build)
        run: docker compose -f laradock/docker-compose.yml exec -T workspace npm run build

      - name: Run Laravel tests
        run: docker compose -f laradock/docker-compose.yml exec -T workspace php artisan test --parallel --stop-on-failure

      - name: Stop Docker containers
        if: always()
        run: docker compose -f laradock/docker-compose.yml down
